version: '3.8'

services:
  api:
    container_name: api-bolsiyo
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn start:dev api-bolsiyo
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=bolsiyo
      - MYSQL_PASSWORD=bolsiyo
      - MYSQL_DATABASE=bolsiyo
      - MYSQL_PORT=3306
      - AT_SECRET=at-secret
      - RT_SECRET=rt-secret
    networks:
      - bolsiyo_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bolsiyo
      MYSQL_USER: bolsiyo
      MYSQL_PASSWORD: bolsiyo
    container_name: db-bolsiyo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bolsiyo_network

networks:
  bolsiyo_network:
    driver: bridge

volumes:
  db_data: